export const carData = [
    // TODO: source images for each vehicle

    {
        id: 0,
        modelYear: 2025,
        manufacturer: "Honda",
        modelName: "CR-V",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain:  ["ICE", "HEV"],
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "commuting", "trailheads"]
    },
    {
        id: 1,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "Bronco Sport",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain:  ["ICE"],
        imageSource: "",
        tags: ["commuting", "running-errands", "trailheads"]
    },
    {
        id: 2,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "RAV4",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain:  ["ICE", "HEV", "PHEV"],
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "ride-sharing", "trailheads"]
    },
    {
        id: 3,
        modelYear: 2025,
        manufacturer: "Kia",
        modelName: "Telluride",
        maxPassengers: 8,
        vehicleShape: "SUV",
        powertrain:  ["ICE"],
        imageSource: "",
        tags: ["family-hauling", "running-errands", "ride-sharing"]
    },
    {
        id: 4,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "Bronco",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain:  ["ICE"],
        imageSource: "",
        tags: ["desert-dunes", "rocky-trails", "trailheads"]
    },
    {
        id: 5,
        modelYear: 2026,
        manufacturer: "Hyundai",
        modelName: "Palisade",
        maxPassengers: 8,
        vehicleShape: "SUV",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["family-hauling", "running-errands", "ride-sharing"]
    },
    {
        id: 6,
        modelYear: 2025,
        manufacturer: "Jeep",
        modelName: "Grand Cherokee L",
        maxPassengers: 7,
        vehicleShape: "SUV",
        powertrain: ["ICE", "PHEV"],
        imageSource: "",
        tags: ["family-hauling", "running-errands", "ride-sharing", "trailheads"]
    },
    {
        id: 7,
        modelYear: 2025,
        manufacturer: "Jeep",
        modelName: "Wrangler",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain: ["ICE", "PHEV"],
        imageSource: "",
        tags: ["desert-dunes", "rocky-trails", "trailheads"]
    },
    {
        id: 8,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "4Runner",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["family-hauling", "running-errands", "rocky-trails", "trailheads"]
    },
    {
        id: 9,
        modelYear: 2025,
        manufacturer: "Subaru",
        modelName: "Forester",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing", "trailheads"]
    },
    {
        id: 10,
        modelYear: 2025,
        manufacturer: "Chevrolet",
        modelName: "Suburban",
        maxPassengers: 8,
        vehicleShape: "SUV",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["family-hauling", "towing-hauling", "transport-eq", "ride-sharing"]
    },
    {
        id: 11,
        modelYear: 2025,
        manufacturer: "Jeep",
        modelName: "Grand Wagoneer",
        maxPassengers: 7,
        vehicleShape: "SUV",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["family-hauling", "towing-hauling", "ride-sharing", "trailheads"]
    },
    {
        id: 12,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "Expedition",
        maxPassengers: 8,
        vehicleShape: "SUV",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["family-hauling", "towing-hauling", "transporting-eq", "ride-sharing", "trailheads"]
    },
    {
        id: 13,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "Sequoia",
        maxPassengers: 7,
        vehicleShape: "SUV",
        powertrain: ["HEV"],
        imageSource: "",
        tags: ["family-hauling", "towing-hauling", "transporting-eq", "ride-sharing", "trailheads"]
    },
    {
        id: 14,
        modelYear: 2025,
        manufacturer: "Chevrolet",
        modelName: "Trax",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["commuting", "running-errands"]
    },
    {
        id: 15,
        modelYear: 2025,
        manufacturer: "Hyundai",
        modelName: "Ioniq 5",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 16,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "Mustang Mach-E",
        maxPassengers: 5,
        vehicleShape: "SUV",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 17,
        modelYear: 2026,
        manufacturer: "Rivian",
        modelName: "R1S",
        maxPassengers: 7,
        vehicleShape: "SUV",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "trailheads", "desert-dunes", "straight-line"]
    },
    {
        id: 18,
        modelYear: 2025,
        manufacturer: "Kia",
        modelName: "EV9",
        maxPassengers: 6,
        vehicleShape: "SUV",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 19,
        modelYear: 2025,
        manufacturer: "Nissan",
        modelName: "Versa",
        maxPassengers: 5,
        vehicleShape: "car",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 20,
        modelYear: 2025,
        manufacturer: "Honda",
        modelName: "Civic",
        maxPassengers: 5,
        vehicleShape: "car",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 21,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "Prius",
        maxPassengers: 5,
        vehicleShape: "car",
        powertrain: ["HEV", "PHEV"], 
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 22,
        modelYear: 2025,
        manufacturer: "Honda",
        modelName: "Accord",
        maxPassengers: 5,
        vehicleShape: "car",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 23,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "Camry",
        maxPassengers: 5,
        vehicleShape: "car",
        powertrain: ["HEV"], 
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 24,
        modelYear: 2025,
        manufacturer: "Kia",
        modelName: "K5",
        maxPassengers: 5,
        vehicleShape: "car",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["commuting", "running-errands", "ride-sharing"]
    },
    {
        id: 25,
        modelYear: 2025,
        manufacturer: "Aston Martin",
        modelName: "Vantage",
        maxPassengers: 2,  
        vehicleShape: "coupe", 
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["time-attack", "thrill-rides", "straight-line"]
    },
    {
        id: 26,
        modelYear: 2025,
        manufacturer: "BMW",
        modelName: "2-Series",
        maxPassengers: 4,
        vehicleShape: "coupe",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["thrill-rides", "running-errands", "commuting"]
    },
    {
        id: 27,
        modelYear: 2025,
        manufacturer: "BMW",
        modelName: "M4",
        maxPassengers: 4,
        vehicleShape: "coupe",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["time-attack", "thrill-rides", "straight-line"]
    },
    {
        id: 28,
        modelYear: 2025,
        manufacturer: "Chevrolet",
        modelName: "Corvette",
        maxPassengers: 2,
        vehicleShape: "coupe",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["time-attack", "thrill-rides", "straight-line"]
    },
    {
        id: 29,
        modelYear: 2025,
        manufacturer: "Mercedes-Benz",
        modelName: "AMG CLE53", 
        maxPassengers: 4,
        vehicleShape: "coupe",
        powertrain: ["ICE"], // mild hybrid
        imageSource: "",
        tags: ["thrill-rides", "straight-line"]
    },
    {
        id: 30,
        modelYear: 2025,
        manufacturer: "Porsche",
        modelName: "911",
        maxPassengers: 4,
        vehicleShape: "coupe",
        powertrain: ["ICE", "HEV"],
        imageSource: "",
        tags: ["time-attack", "thrill-rides", "straight-line"]
    },
    {
        id: 31,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "GR 86",
        maxPassengers: 4,
        vehicleShape: "coupe", 
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["thrill-rides", "running-errands"]
    },
    {
        id: 32,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "GR Supra",
        maxPassengers: 4,
        vehicleShape: "coupe", 
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["thrill-rides", "straight-line"]
    },
    {
        id: 33,
        modelYear: 2025,
        manufacturer: "Mercedes-Benz",
        modelName: "E-Class All-Terrain",
        maxPassengers: 5,
        vehicleShape: "wagon",
        powertrain: ["ICE"], // mild hybrid
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "trailheads"]
    },
    {
        id: 34,
        modelYear: 2025,
        manufacturer: "Audi",
        modelName: "A6 Allroad",
        maxPassengers: 5,
        vehicleShape: "wagon",  
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "trailheads"]
    },
    {
        id: 35,
        modelYear: 2025,
        manufacturer: "Subaru",
        modelName: "Outback",
        maxPassengers: 5,
        vehicleShape: "wagon",  
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "trailheads"]
    },
    {
        id: 36,
        modelYear: 2025,
        manufacturer: "Volvo",
        modelName: "V60 Cross Country",
        maxPassengers: 5,
        vehicleShape: "wagon",  
        powertrain: ["ICE"], // mild hybrid
        imageSource: "",
        tags: ["family-hauling", "commuting", "running-errands", "trailheads"]
    },
    {
        id: 37,
        modelYear: 2025,
        manufacturer: "Audi",
        modelName: "RS6 Avant",
        maxPassengers: 5,
        vehicleShape: "wagon",  
        powertrain: ["ICE"], // mild hybrid
        imageSource: "",
        tags: ["family-hauling", "time-attack", "thrill-rides", "straight-line"]
    },
    {
        id: 38,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "Transit",
        maxPassengers: 15,
        vehicleShape: "van",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["towing-hauling", "transporting-eq"]
    },
    {
        id: 39,
        modelYear: 2025,
        manufacturer: "Chevrolet",
        modelName: "Express",
        maxPassengers: 15,
        vehicleShape: "van",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["towing-hauling", "transporting-eq"]
    },
    {
        id: 40,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "e-Transit",
        maxPassengers: 2,
        vehicleShape: "van",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["transporting-eq"]
    },
    {
        id: 41,
        modelYear: 2025,
        manufacturer: "Mercedes-Benz",
        modelName: "eSprinter",
        maxPassengers: 3,
        vehicleShape: "van",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["transporting-eq"]
    },
    {
        id: 42,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "Sienna",
        maxPassengers: 8,
        vehicleShape: "van",
        powertrain: ["HEV"],
        imageSource: "",
        tags: ["family-hauling", "running-errands", "ride-sharing"]
    },
    {
        id: 43,
        modelYear: 2025,
        manufacturer: "Chrysler",
        modelName: "Pacifica",
        maxPassengers: 7, 
        vehicleShape: "van",
        powertrain: ["ICE","PHEV"],
        imageSource: "",
        tags: ["family-hauling", "running-errands", "ride-sharing"]
    },
    {
        id: 44,
        modelYear: 2025,
        manufacturer: "Kia",
        modelName: "Carnival",
        maxPassengers: 8, 
        vehicleShape: "van",
        powertrain: ["ICE", "HEV"], 
        imageSource: "",
        tags: ["family-hauling", "running-errands", "ride-sharing"]
    },
    {
        id: 45,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "F-150 Raptor",
        maxPassengers: 5,
        vehicleShape: "truck",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["towing-hauling", "transporting-eq", "desert-dunes", "rocky-trails", "trailheads", "straight-line"]
    },
    {
        id: 46,
        modelYear: 2025,
        manufacturer: "Chevrolet",
        modelName: "Silverado",
        maxPassengers: 6,
        vehicleShape: "truck",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["towing-hauling", "transporting-eq", "rocky-trails", "trailheads"]
    },
    {
        id: 47,
        modelYear: 2025,
        manufacturer: "Ford",
        modelName: "Maverick",
        maxPassengers: 5, 
        vehicleShape: "truck",
        powertrain: ["HEV","ICE"], 
        imageSource: "",
        tags: ["commuting", "running-errands", "towing-hauling", "transporting-eq", "trailheads"]
    },
    {
        id: 48,
        modelYear: 2025,
        manufacturer: "Nissan",
        modelName: "Frontier",
        maxPassengers: 5, 
        vehicleShape: "truck",
        powertrain: ["ICE"],
        imageSource: "",
        tags: ["towing-hauling", "transporting-eq", "trailheads"]
    },
    {
        id: 49,
        modelYear: 2025,
        manufacturer: "Toyota",
        modelName: "Tacoma",
        maxPassengers: 5, 
        vehicleShape: "truck",
        powertrain: ["ICE","HEV"],
        imageSource: "",
        tags: ["towing-hauling", "transporting-eq", "desert-dunes", "rocky-trails", "trailheads"]
    },
    {
        id: 50,
        modelYear: 2025,
        manufacturer: "Rivian", 
        modelName: "R1T", 
        maxPassengers: 5,
        vehicleShape: "truck",
        powertrain: ["BEV"],
        imageSource: "",
        tags: ["transporting-eq", "rocky-trails", "trailheads", "straight-line"]
    }
];